Belval/TextRecognitionDataGenerator

- TextRecognitionDataGenerator/background_generator.py
If "picture.size[0] == width" or "picture.size[1] == height", there will be an Exception beacause the code "random.randint(0, 0)", so I judge if "picture.size[0] == width" or "picture.size[1] == height" to prevent this happen.
> solve the error for "random.randint(0, 0)"

- TextRecognitionDataGenerator/computer_text_generator.py
- TextRecognitionDataGenerator/data_generator.py
- TextRecognitionDataGenerator/handwritten_text_generator.py
This PR adds support for the `-tc` parameter for handwritten text.
> Add text_color support for handwritten

- TextRecognitionDataGenerator/run.py
- tests.py
As said in #59 : we can generate picture with only one font pass by argument
> Add argument font

- TextRecognitionDataGenerator/background_generator.py
Update the procedure of resizing the background image. 
1. It's possible for a really small background image that after resizing the width to the necessary text width, the height of the background image is still less than the necessary text height. Hence the `elif` is changed to `if`.
1. Also, `pic.resize` seems better than `pic.thumbnail` for resizing the small background image.
> Update the procedure of resizing the image.

- README.md
- tests.py
- trdg/generators/from_strings.py
Big oversight that made the helper Generators pretty close to useless as they were not returning the label with the generated image.
Fixed tests and code to return a tuple.
> Add label to generator output

- README.md
- setup.py
- tests.py
- trdg/computer_text_generator.py
- trdg/data_generator.py
- trdg/generators/__init__.py
- trdg/generators/from_strings.py
- trdg/run.py
#109 highlighted that the script installation was not working on Windows. The error was not identified because there are no tests on Windows.
Replaces `scripts` with `console_scripts`.
Fixes #109
> Use console_script for Windows compatibility

- trdg/background_generator.py
Whatever use this repo by clone or pypi package, when background_type=3, it will raise FileNotFoundError: [Errno 2] No such file or directory: './pictures', because the path is not correct. We should get script path and join it.
> Fix picture path, when using import

- trdg/handwritten_text_generator.py
Added:
- Function to download model weights from Git repo
- Fix loading of files
- Fix for `TypeError: argument 1 must be read-only bytes-like object, not memoryview`
- Compatible with TensorFlow 1.15
- Added image mask to `generate()`
> add download model weights + fix for mask

- trdg/data_generator.py
Follows after: https://github.com/Belval/TextRecognitionDataGenerator/pull/117
> Add mask for handwritten text

- tests.py
- trdg/run.py
Now user can indicate what dictionary to use, by an argument like ```--dict [PATH_TO_DICT].txt```.
Related issue: #123
> Add argument dict

- setup.py
- tests.py
Use MD5 for comparison was a pain because it would yield inconsistent results based on the systems PNG and JPEG libraries.
Using `diffimg` allows us to do a more forgiving matching, which will still trigger on different images while allowing some differences.
> Use diff instead of MD5 for tests

- trdg/computer_text_generator.py
Generating vertical text images would always result in black text, even when a different text colour was specified.  I realized that the `ImageDraw.Draw` object used to draw on the mask image actually draws on the text image, so I adjusted it to draw on the mask image.
Fixes #132
> Fixed vertical text colouring bug

- trdg/data_generator.py
- trdg/utils.py
When generating strings containing whitespace characters only the characters of the first word would get bboxes, I fixed this (inside mask_to_bboxes under utils.py). 
Also, when passing 2 as the -obb argument, the bboxes are written in a <image>.box file in the format <symbol> <left> <bottom> <right> <top> <page> ready to train Tesseract.
> Added whitespace bbox support and Tesseract format supported bboxes

- trdg/generators/from_random.py
- trdg/generators/from_wikipedia.py
- trdg/string_generator.py
Fixing duplicates in random/wikipedia generator.
The code below can be used on the current version to reproduce the bug, every label will be generated 3 times. It can also be run after the fix for validation.
```
from trdg.generators import GeneratorFromRandom
import numpy as np
random_generator = GeneratorFromRandom(count=3000, allow_variable=True, length=10)
labels = []
for _, label in random_generator:
labels.append(label)
values, counts = np.unique(labels, return_counts=True)
print(values)
print(counts)
print(len(labels))
print(len(set(labels)))
```
> fix duplicates in random/wikipedia generator and adding timeout to wikipedia requests

- requirements.txt
numpy can be installed within openCV, no need to install it separately.
In addition, the specified range of versions for numpy is causing the following error (conflicting dependencies):
```
ERROR: Cannot install -r requirements.txt (line 4) and numpy<1.17 and >=1.16.4 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested numpy<1.17 and >=1.16.4
opencv-python 4.5.2.52 depends on numpy>=1.19.3
The user requested numpy<1.17 and >=1.16.4
opencv-python 4.5.1.48 depends on numpy>=1.19.3
The user requested numpy<1.17 and >=1.16.4
opencv-python 4.4.0.46 depends on numpy>=1.19.3
The user requested numpy<1.17 and >=1.16.4
opencv-python 4.4.0.44 depends on numpy>=1.17.3
The user requested numpy<1.17 and >=1.16.4
opencv-python 4.4.0.42 depends on …
```
> fix: conflicting dependencies error

- trdg/run.py
Arabic is a right-left language so we need to write its text in that way and this PR fixes it.
> fix: Correct Bidi Arabic Text

- trdg/run.py
I guess the original commit "Remove space from label when space width is 0" was intended to do this. Let me know if I didn't get it right.
> Remove space in format 2 label when space width set to zero

- requirements.txt
- trdg/generators/from_strings.py
This pull request to support generating images containing Right-to-left strings (like in Arabic, Persian, Urdu, etc.)
-----
Th next script will generate an Image contains an Arabic (RTL) string. This's what the project is currently generating.
```python
from trdg.generators import GeneratorFromStrings
generator = GeneratorFromStrings(
['ذهبتُ إلى الشيخ زويد'],
blur=1,
size=128,
random_blur=True,
language="ar"
)
for img, lbl in generator:
if img:
img.save("without-rtl.png")
break
```
The output will look like
-----
While, after this PR, the next code will able to generate a valid image with an RTL string
```python
from trdg.generators import GeneratorFromStrings
generator = GeneratorFromStrings(
['ذهبتُ إلى الشيخ زويد'],
blur=1,
size=128,
random_blur=True,
rtl=True, # Look HERE !! …
```
> support reshaping RTL strings

- trdg/data_generator.py
Ran into ```PIL ValueError: image has wrong mode``` when generating text with own background images.
Reason: background images are in P mode (palettized) and therefore failed the gaussian_filter.
Fix: convert the background images first.
> [BUG] resolve PIL ValueError: image has wrong mode on background image

- trdg/generators/from_dict.py
- trdg/generators/from_random.py
- trdg/generators/from_wikipedia.py
After generating more than 1000 images using a generator, 1000 more image were generated every step (instead of after an additional 1000 steps). This lead to a performance decrease, especially for the Wikipedia generator where generation of 1000 samples is especially costly. 
Also introduces the `batch_size` variable so that not too many samples are generated if count is much lower than the default (which was 1000). For reasons mentioned above, this is especially helpful for the Wikipedia generator.
> Fix Generator Performance for Large Amounts of Samples

- trdg/data_generator.py
`PIL.ImageFilter.GaussianBlur` method allows decimal blur values, but using `random.randint` to generate a blur between 0 and the limit, will make the use of decimals generate an error, since you can't use an decimal in the randint method, and even if you could, it won't return decimal values. Then, the integer blur was always either too few or too agressive for TR. With this changes, it will be possible to find a number between these two extremes.
Note: It might have no effect since the radius is probably on pixel units, and this unit can't be decimal, but I didn't took the time to figure it out.
> Allowing random blur to be decimal
